IF
	See("AC#W#AG2")  // Annia Graustiefel
	Global("AC#W_Annia_Staircase","GLOBAL",10)
THEN
	RESPONSE #100
		Attack("AC#W#AG2")  // Annia Graustiefel
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
END

IF
	See(NearestEnemyOf(Myself))
	Global("AC#W_Annia_Staircase","GLOBAL",10)
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),6)
END

