IF
	GlobalGT("AC#W_BaatezuJob","GLOBAL",0)
	GlobalLT("AC#W_BaatezuJob","GLOBAL",10)
THEN
	RESPONSE #100
		DestroySelf()
END

IF
	GlobalGT("StaircaseAftermath","AC#W30",0)
THEN
	RESPONSE #100
		DestroySelf()
END

IF
	See(NearestEnemyOf(Myself))
	OR(2)
		Range(LastSeenBy(Myself),10)
		HPPercentLT(Myself,50)
	!StateCheck(Myself,STATE_INVISIBLE)
THEN
	RESPONSE #100
		ApplySpell(Myself,WIZARD_INVISIBILITY)  // SPWI206.SPL (Unsichtbarkeit)
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Delay(6)
THEN
	RESPONSE #20
		SpellNoDec(LastSeenBy(Myself),WIZARD_BLINDNESS)  // SPWI106.SPL (Blindheit)
		Continue()
	RESPONSE #20
		SpellNoDec(LastSeenBy(Myself),WIZARD_SLEEP)  // SPWI116.SPL (Schlaf)
		Continue()
	RESPONSE #20
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHARM_PERSON)  // SPWI104.SPL (Personen bezaubern)
		Continue()
	RESPONSE #20
		SpellNoDec(LastSeenBy(Myself),WIZARD_HOLD_PERSON)  // SPWI306.SPL (Personen festhalten)
		Continue()
	RESPONSE #20
		SpellNoDec(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Farbkugel)
		Continue()
	RESPONSE #20
		SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magisches Geschoﬂ)
		Continue()
END

